version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:14
    container_name: inventory-control-db
    volumes:
      - db-data:/var/lib/postgresql/inventory_control_db_development/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password